include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - android/**
    - build/**
    - '*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: warning
    dead_code: error
    avoid_print: error

linter:
  rules:
    prefer_single_quotes: true
    avoid_annotating_with_dynamic: true
