include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - android/**
    - build/**
    - '*.g.dart'
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: warning
