# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    patch:
      default:
        target: 0
        threshold: 100%
    project:
      default:
        target: 0
        threshold: 100%

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: files
