name: laera
description: Laera for Android.

version: "0.1.0"

environment:
  sdk: ">=2.10.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1
  path: ^1.7.0
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/logo.png"
