name: laera
description: Laera is the Android application for words learning

version: "0.2.1"

publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ^1.22.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  path: ^1.7.0
  sqflite: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  build_runner: ^1.10.0
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/logo.png
