name: laera
description: Laera is the Android application for words learning

version: "0.2.1"

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: launcher_icon
  image_path: assets/icon/logo.png

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.6.0-nullsafety.2
  hive_flutter: 1.0.0-nullsafety.0
  json_annotation: ^4.0.0
  path: ^1.7.0
  path_provider: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.0
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.0
  json_serializable: ^4.0.0
  lint: ^1.3.0
