default_platform(:android)

platform :android do
  lane :build_aab do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "test")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle", "--build-number=#{build_number}")
    end
  end

  lane :build_apk do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "packages", "get")
      sh("flutter", "test")
      sh("flutter", "clean")
      sh("flutter", "build", "apk", "--build-number=#{build_number}")
    end
  end

  lane :build_apk_dev do
    build_number = number_of_commits()
    Dir.chdir "../.." do
      sh("flutter", "build", "apk", "--debug", "--build-number=#{build_number}")
    end
  end

  lane :release_alpha do
    build_aab
    upload_to_play_store(
      track: 'alpha',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
