name: Android

on:
  push:
    tags: [ v* ]

env:
  flutter_version: 1.22.x

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits, tags, etc

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}

      - name: Get Ruby dependencies from cache
        uses: actions/cache@v2
        with:
          path: android/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Get Flutter dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-${{ env.flutter_version }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.flutter_version }}-pub-

      - run: make ci-before

      - name: Install Flutter dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Install secrets
        run: |
          mkdir -p android/fastlane/keys
          echo "${{ secrets.KEYSTORE_JKS_B64 }}" | base64 -d > android/fastlane/keys/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES_B64 }}" | base64 -d > android/fastlane/keys/keystore.properties
          echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON_B64 }}" | base64 -d > android/fastlane/keys/google_play_api_key.json

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: release_alpha
          subdirectory: android
          bundle-install-path: vendor/bundle
          skip-tracking: true
