name: Android

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # `0` means fetch all commits, tags, etc
          fetch-depth: 0
      
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22'

      - run: |
          mkdir -p android/fastlane/keys
          echo "${{ secrets.KEYSTORE_JKS_B64 }}" | base64 -d > android/fastlane/keys/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES_B64 }}" | base64 -d > android/fastlane/keys/keystore.properties
          echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON_B64 }}" | base64 -d > android/fastlane/keys/google_play_api_key.json

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'release_alpha'
          subdirectory: 'android'
          skip-tracking: true
