name: Flutter-CI

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.1'
    - run: flutter pub get
    - run: flutter test
