name: Flutter

on:
  pull_request:
    branches: [ stable ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22'
    - run: flutter pub get
    - run: flutter test
