name: Pull request

on: [pull_request]

env:
  FLUTTER_VERSION: 3.0.x

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Download Git sources
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get Flutter dependencies from cache
        uses: actions/cache@v3
        with:
          path: .pub-cache
          key: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}-pub-

      - name: Run lint and tests
        run: make ci-before ci

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
          verbose: true
          file: ./coverage/lcov.info
          flags: unittests
