name: Release to Google Play

on:
  release:
    types: [published]

env:
  FLUTTER_VERSION: 3.0.x
  RUBY_VERSION: "3.1"

jobs:
  lint-test-and-release:
    name: Lint, test, and release to Google Play
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/android/Gemfile
    steps:
      - name: Download Git sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all commits, tags, etc

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Get Flutter dependencies from cache
        uses: actions/cache@v3
        with:
          path: .pub-cache
          key: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.FLUTTER_VERSION }}-pub-

      - name: Run lint and tests
        run: make ci-before ci

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install secrets
        run: |
          mkdir -p android/fastlane/keys
          echo "${{ secrets.KEYSTORE_JKS_B64 }}" | base64 -d > android/fastlane/keys/keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES_B64 }}" | base64 -d > android/fastlane/keys/keystore.properties
          echo "${{ secrets.GOOGLE_PLAY_API_KEY_JSON_B64 }}" | base64 -d > android/fastlane/keys/google_play_api_key.json

      - name: Build and release APK
        uses: maierj/fastlane-action@v2.2.1
        with:
          lane: release_alpha
          subdirectory: android
          bundle-install-path: vendor/bundle
          skip-tracking: true

      - name: Send built APK to Telegram dev chat
        run: |
          output_file_dir=build/app/outputs/apk/release
          output_file_name=$(ls $output_file_dir | grep apk)
          curl \
            -F chat_id=${{ secrets.TELEGRAM_DEV_CHAT }} \
            -F document=@$output_file_dir/$output_file_name \
            -F parse_mode=MarkdownV2 \
            -F caption='
          🚀 release build

          repo: `${{ github.repository }}`
          workflow: `${{ github.workflow }}`
          branch/tag: `${{ github.ref }}`
          triggered by: `${{ github.actor }}`
          commit hash: `${{ github.sha }}`
          ' \
            https://api.telegram.org/bot${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}/sendDocument
